### PR TITLE
Add code of conduct template

### PR DESCRIPTION
**Pull request by bhantsi**
## Link to the Issue

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

## Description of your PR

(Provide a description of what this PR does.)

## Screenshots (if applicable)

(Add screenshots of the visual changes in the project)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by s-katte** [comment]
Hey @bhantsi, the changes look good to me. 
Please answer the appropriate questions mention in the PR template and then it is good to go.

**Comment by gridhead** [comment]
@s-katte please keep a check on answers and make sure that they are received well under six hours - failing to which, the PR might be prematurely closed.

**Comment by s-katte** [comment]
I would take that into consideration @t0xic0der.
@bhantsi, within the next 5hrs if needful changes are not done, this PR will be marked as **invalid** .

**Comment by bhantsi** [comment]
@s-katte and @t0xic0der what exactly do you want me to add/removed

**Comment by s-katte** [comment]
> @s-katte and @t0xic0der what exactly do you want me to add/removed

You have to edit the PR template which is provided by answering the questions mentioned there @bhantsi

**Comment by s-katte** [comment]
I am labeling this invalid.

**Pull request closed without merging**
