### PR TITLE
[Feat] Add suggestion and autoclose tag, bracket while writing code

### LINKED ISSUE #33: Basic suggestions while writing code.
## 🚀 Feature

Suggestions while writing code.

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes.

## Pitch

To give users a native editor feel, basic suggestions would do a better job to enhance their experience while developing great ideas.

### PR DESCRIPTION
**Pull request by dao-phuong**
## Link to the Issue

https://github.com/s-katte/Sketchify/issues/33

## Description of your PR

- Add html, css, js suggestion
- Add auto close tag, bracket
- Change mode of html editor from 'xml' to 'text/html' to provide html tag suggestion feature

## Screenshots (if applicable)
Screen Shot 2020-10-22 at 16 10 40
Screen Shot 2020-10-22 at 16 11 00
Screen Shot 2020-10-22 at 16 11 32

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by s-katte — CHANGES_REQUESTED** [review]
Hey @dao-phuong, the feature looks good, but the suggestions are popping up unnecessarily while we try to use ```up``` and ```down``` arrow keys. 
Please make the changes accordingly to keep the user experience better.

**Comment by dao-phuong** [comment]
@s-katte Should I also escape `left` and `right` arrow?

Updated: Format test have not passed. I wonder where is it wrong :'(

**Comment by s-katte** [comment]
> @s-katte Should I also escape `left` and `right` arrow?

Yes please, also escape various other not-needed keys like ```ctrl```
As you can see, it is suggesting unnecessarily suggesting while putting the content, and there is no match, it is just suggesting everything.

Screenshot from 2020-10-23 09-42-53

**Comment by dao-phuong** [comment]
I've updated list unnecessary key. About the showing suggestion when putting content in html, I haven't found any solution yet. I still working on this, please let me know if you have any idea.

Updated: I finished it

**Comment by dao-phuong** [comment]
Only show suggestion when user press key in range [a-zA-Z] instead of escape unnecessary key, so we don't need to worry about some special key is not escaped. Does it make sense @s-katte. If you ok with it, I'll update code

**Review by s-katte — APPROVED** [review]
> Only show suggestion when user press key in range [a-zA-Z] instead of escape unnecessary key, so we don't need to worry about some special key is not escaped. Does it make sense @s-katte. If you ok with it, I'll update code

Now it is working well. Thank you for your contribution.

**Pull request merged**
