### PR TITLE
Downloadable webpage

### LINKED ISSUE #4: Make the prototype downloadable in the form of respective file extensions by giving a button.
The user can download the prototype after doing some work, although the code and scripts will be retained unless the browser data is not cleared. It would be great to have this option for convenience.

### PR DESCRIPTION
**Pull request by VaibhavSaini19**
## Link to the Issue

Fixes #4 

## Description of your PR

Added 3 buttons to download the HTML, CSS and JS codes. Also, manually linked the css and js files in the html file for proper style and js rendering. Since, a Navbar is not present right now, the buttons can be styled later as per the navbar style for consistency

## Screenshots (if applicable)

Download buttons
Screenshot (165)

Saved files 
Screenshot (164)

## Test Plan

Added 3 functions that download the respective files. Verified by downloading the files and opening the index.html in browser, which successfully render with the css and js

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by s-katte — CHANGES_REQUESTED** [review]
The functionality is working completely fine now @VaibhavSaini19.
Just a few changes needed for enhancing user experience:
- Removal of extra indentation from HTML file.
- Formatting of the scripts in HTML by using standard Emmet Abbreviation(keeping default title as ```Title```
- Change of button colors to match the apparent theme (you have options like ```#3C3E44```, ```#1F2023```, ```#767676```, can choose any of these, or can suggest others too)
- Code clean(_removal of warnings_) by removing extra dependencies imported that are not in use and also using buttons instead of 3 anchor tags to avoid warnings that show up while running project in dev.

**Comment by VaibhavSaini19** [comment]
@s-katte We need to use anchor tags as only they have `href` and `download` attribute. Made rest of the requested changes

**Review by s-katte — CHANGES_REQUESTED** [review]
we can provide default values for ```href``` and that may avoid warnings, can't we?

**Comment by VaibhavSaini19** [comment]
> we can provide default values for `href` and that may avoid warnings, can't we?

I tried that already, but it doesn't work

**Comment by VaibhavSaini19** [comment]
> we can provide default values for `href` and that may avoid warnings, can't we?

Giving `href=" "` did the job

**Review by s-katte — APPROVED** [review]
Looks great now!
Merging it, efforts appreciated :smile:

**Pull request merged**
