### PR TITLE
Feat: Alert the user before closing tab/window

### LINKED ISSUE #11: Alert the user before closing the tab/window.
Although every change is persisted across the browser, it would be great to have an alert before closing the working tab/window.

### PR DESCRIPTION
**Pull request by akaash11**
#11 Alert the user before closing tab/window 
Updated file components => App.js
Added useEffect to listen to beforeunload event.

### CODE REVIEW

**Comment by s-katte** [comment]
Hey @akaash11, it would be great if I get to see the screenshot of the working alert before closing the tab/window.

**Comment by akaash11** [comment]
PFB screenshot of alert:
image

Please review PR and let me know if any feedback.
Once you are satisfied please add labels "hacktoberfest" and "hacktoberfest-accepted".

Thank you.

**Comment by gridhead** [comment]
> Please accept the PR and add labels "hacktoberfest" and "hacktoberfest-accepted".

As much as we are thankful for your contributions here @akaash11, please refrain from suggesting maintenance actions to the repo contributors as that might end up sounding disrespectful to the maintainers. We understand your priorities and would do the necessary in good faith.

@s-katte For your reference.

**Comment by akaash11** [comment]
My bad @t0xic0der I didn't mean it in that way. I will reframe.

**Comment by s-katte** [comment]
@t0xic0der, thanks for your attention.

@akaash11, I have looked into it, the change works fine, appreciated your efforts.
Feel free to :star: the repo if this was worth your time.

**Pull request merged**
