### PR TITLE
Added nav-bar and CSS changes

### PR DESCRIPTION
**Pull request by im-adithya**
## Sketchify now has a nav-bar!

-With download buttons for the three files as mentioned
-And input for the file name which gets updated in the title as well

I also added
-Scroll bar inside the editing panes
-And other small CSS changes like the font of headings of panes

I'm sorry if these changes felt unnecessary 😬

## Screenshots

Screenshot (267)

## Test Plan

-I've changed the scroll bar for which I checked it multiple times in each pane
-I've made sure that the window stays at 100vh all the time
-I downloaded the file and checked it to make sure that the title tag is updated or not

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

And finally, Thank You!! ☺☺
This was indeed a great project for me to work on!

### CODE REVIEW

**Review by s-katte — CHANGES_REQUESTED** [review]
Hey @im-adithya, changes are appreciated, requesting these changes:

- **Title** is not persisted if the browser is close/refreshed/reopened, as it should be. So make it persistent.
- Please keep the title of the project at the center and the logo to the left.
- Change navbar colors to match the apparent theme (you have options like #3C3E44, #1F2023, #767676, can choose any of these, or can suggest others too)
- For the sake of matching PR with issues, we would like to have only changes requested in the corresponding issue.
- We would encourage you to make a new issue for your other changes (scroll bar and height) and get yourself assigned there followed by making a new PR :smile: 
- Please follow the PR template provided, so as to keep the flow smooth.

Please do the needful and discuss if any other issues.

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@im-adithya while you are at it, it would be great if you could install fontawesome icons through npm instead of using the cdn. Also, use a download icon like [this](https://fontawesome.com/icons/download?style=solid). Reduce the vertical padding slightly as well, more focus should be on editors rather than the navbar

**Comment by s-katte** [comment]
Hey @im-adithya, you are requested to make changes in this PR itself, no need to make another PR for the same issue. Please reopen it

**Comment by im-adithya** [comment]
I unknowingly deleted the previously forked repo and forked it again to update it... that's why I opened a new one

**Comment by im-adithya** [comment]
Also can you please tell me how can I update my forked repo if this happens?
Thanks in advance!

**Comment by s-katte** [comment]
> Also can you please tell me how can I update my forked repo if this happens?
Thanks in advance!

The deletion of repo is irreversible in my knowledge.

So from next time just keep your forked repo updated by fetching it once in while from master to avoid conflicts.

you can  add to this answer - @t0xic0der and @VaibhavSaini19

**Comment by VaibhavSaini19** [comment]
> Also can you please tell me how can I update my forked repo if this happens?

You can `rebase` or merge the master branch from the original repo back to your fork. 
- GitHub Desktop (easiest):
Fetch upstream, click on branches, click on `select a branch to merge into master` and choose `upstream/master`, confirm and push origin
- From CLI:
Add remote, fetch upstream, checkout master, rebase using `git rebase upstream/master`
- In browser:
On your fork's master branch, click on `Pull request` and click on `switch the base` (or you can manually choose your repo as base repo with master branch, and the original repo as head repo with master branch, in the dropdowns), create PR, and choose Rebase from dropdown in the merge button

**Comment by im-adithya** [comment]
@s-katte @VaibhavSaini19 Thank you so much for your guidance! You people are amazing to work with! ✨

**Pull request closed without merging**
